In [1]:
import numpy as np

In [16]:
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
for cell in a:
    print(cell)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [7]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [8]:
for i in np.nditer(a,order='C'):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [9]:
for i in np.nditer(a,order='F'):
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


In [10]:
for i in np.nditer(a,order='F',flags=['external_loop']):
    print(i)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [22]:
for i in np.nditer(a,op_flags=['readwrite']):
    i[...]=i*2

In [23]:
a

array([[ 0,  4,  8, 12],
       [16, 20, 24, 28],
       [32, 36, 40, 44]])

In [24]:
b

22

In [25]:
b=np.arange(3,15,4).reshape(3,1)

In [26]:
b

array([[ 3],
       [ 7],
       [11]])

In [27]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
4 3
8 3
12 3
16 7
20 7
24 7
28 7
32 11
36 11
40 11
44 11
